source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LHInfoTextfield_Example', :exclusive => true do
  pod "LHInfoTextfield", :path => "../"
end

target 'LHInfoTextfield_Tests', :exclusive => true do
  pod "LHInfoTextfield", :path => "../"

  
end
